### ISSUE TITLE
 Please add the Linux net namespace,  like: wireguard.

### ISSUE THREAD

**Issue by Aromate** [tun2proxy/tun2proxy#100]
---
name: Net namespace request
about: Add the linux net namespace support, like wireguard. Can move tun to namespace, proxy namespace net.

---

## Description

``` 
    sudo ip netns add test 
    sudo ./target/release/tun2proxy --setup --proxy "socks5://1.2.3.4:1080"
    sudo ip link set dev tun0 netns test 
```

## Background

TThe Linux net namespace can fake a new net env, like a new OS env.  Can use iptables , and very easy to proxy all net request. like: 
```
   sudo ip netns exec test ip route replace default dev tun0
```

## Expected Behavior

Use tun2proxy create a new tun0, and create a new net namespace test, move the tun0 to test net namespace inside. the tun0 also can be proxy the net requset.

## Additional Information

[boring tun](https://github.com/cloudflare/boringtun)
[wireguard namespace  example](https://www.wireguard.com/netns/)

**Comment by blechschmidt** [comment]
It should work with network namespaces already, although it does not support the slirp use case.

What is the issue with creating a network namespace as follows and running tun2proxy inside?

https://gist.githubusercontent.com/dpino/6c0dca1742093346461e11aa8f608a99/raw/27df052e57009d9ffc1a0ce9d6a8047dc711ad46/ns-inet.sh
