### ISSUE TITLE
ios run fail

### ISSUE THREAD

**Issue by WULINPIN** [tun2proxy/tun2proxy#108]
ios iphone:
13.6
arm64

error:
killed:9

**Comment by ssrlive** [comment]
1. Install Rust Xcode plugin
```
https://github.com/BrainiumLLC/rust-xcode-plugin
```
2. build debug version tun2proxy with `build-aarch64-apple-ios-debug.sh`.
3. build and run your app, attach Xcode debugger to `Network Extension` app.
4. Watch the crash breakpoint, and report it at here.
