### ISSUE TITLE
Exclusion of processes (applications)

### ISSUE THREAD

**Issue by mistek131995** [tun2proxy/tun2proxy#112]
In this utility, I can exclude ip addresses (--bypass), can I exclude processes (applications)? Could such an opportunity appear in the future?

It would also be more convenient to store the list of exceptions in a separate file, and specify it at startup instead of a list of ip addresses.

**Comment by ssrlive** [comment]
Can you give an implementation plan? This solution is required to support the current five platforms. You are welcome to contribute.

**Comment by ssrlive** [comment]
Can you give an implementation plan? This solution should support the current five platforms. You are welcome to contribute.
