### ISSUE TITLE
0.2.18 new version can not working in apline linux

### ISSUE THREAD

**Issue by gogcwy** [tun2proxy/tun2proxy#113]
alpine linux 3.19
0.2.18 gnu and musl error log as below
0.2.16 gnu also have same problem but musl working
```
==============================================================
./tun2proxy_musl -s -p "socks5://127.0.0.1:10808" -t tun --dns over-tcp --dns-add
r 127.0.0.1-b x.x.x.x
thread 'tokio-runtime-worker' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tproxy-config-5.0.1/src/linux.rs:147:67:
called `Result::unwrap()` on an `Err` value: AddrParseError(Ip)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2024-05-08T09:41:08Z ERROR tun2proxy] main_entry error task 3 panicked
==============================================================
./tun2proxy_gnu -s -p "socks5://127.0.0.1:10808" -t tun --dns over-tcp --dns-add
r 127.0.0.1 -b x.x.x.x
-ash: ./tun2proxy_gnu: not found
```

**Comment by ssrlive** [comment]
post your resulets here with this comands:
```
sudo ip -4 route show
```
and 
```
sudo ip -6 route show
```

**Comment by blechschmidt** [comment]
There is a space missing before `-b`.

**Comment by gogcwy** [comment]
ip -4 route show
default via 192.168.0.2 dev eth0  metric 1 onlink
121.121.121.0/24 dev eth1 scope link  src 121.121.121.1
192.168.0.0/24 dev eth0 scope link  src 192.168.0.3

ip -6 route show
fe80::/64 dev eth1  metric 256
fe80::/64 dev eth0  metric 256
multicast ff00::/8 dev eth1  metric 256
multicast ff00::/8 dev eth0  metric 256

===================================
sorry -b is my typing problem 

> post your resulets here with this commands:
> 
> ```
> sudo ip -4 route show
> ```
> 
> and
> 
> ```
> sudo ip -6 route show
> ```

ip -4 route show
default via 192.168.0.2 dev eth0  metric 1 onlink
121.121.121.0/24 dev eth1 scope link  src 121.121.121.1
192.168.0.0/24 dev eth0 scope link  src 192.168.0.3

ip -6 route show
fe80::/64 dev eth1  metric 256
fe80::/64 dev eth0  metric 256
multicast ff00::/8 dev eth1  metric 256
multicast ff00::/8 dev eth0  metric 256

**Comment by gogcwy** [comment]
> There is a space missing before `-b`.

my typing problem in github

**Comment by ssrlive** [comment]
Testing the new version 0.2.19

**Comment by blechschmidt** [comment]
Sorry, I have closed this too early.

**Comment by gogcwy** [comment]
still can not working. can u test alpine 3.19?

only 0.2.16 musl work

alipine default ash:
-------------------------------------------------------------------------------------
./tun2proxy-musl.0.2.19 -p socks5://127.0.0.1:10808 -tun tun -s --dns virtual -b xxx.xxx.xxx.xxx
-ash: ./tun2proxy-musl.0.2.19: not found
-------------------------------------------------------------------------------------
./tun2proxy-gnu.0.2.19 -p socks5://127.0.0.1:10808 -tun tun -s --dns virtual -b xxx.xxx.xxx.xxx
-ash: ./tun2proxy-musl.0.2.19: not found
-------------------------------------------------------------------------------------
bash:
./tun2proxy-musl.0.2.19 -p socks5://127.0.0.1:10808 -tun tun -s --dns virtual -b xxx.xxx.xxx.xxx
-------------------------------------------------------------------------------------
error: the following required arguments were not provided:
  --unshare

Usage: tun2proxy-musl.0.2.19 --proxy <URL> --unshare --tun <name> --setup --dns <strategy> --bypass <IP/CIDR> <ADMIN_COMMAND>...

For more information, try '--help'.
-------------------------------------------------------------------------------------
./tun2proxy-gnu.0.2.19 -p socks5://127.0.0.1:10808 -tun tun -s --dns virtual -b xxx.xxx.xxx.xxx
bash: ./tun2proxy-gnu.0.2.19: cannot execute: required file not found

**Comment by blechschmidt** [comment]
This time, it is probably really due to a typing mistake. The `--tun` argument is missing a second dash.

**Comment by gogcwy** [comment]
> This time, it is probably really due to a typing mistake. The `--tun` argument is missing a second dash.

yes I change to --tun work now ,thanks

======================================
Options:
  -p, --proxy <URL>            Proxy URL in the form proto://[username[:password]@]host:port, where proto is one of socks4,
                               socks5, http. For example: socks5://myname:password@127.0.0.1:1080
  -t, --tun <name>             Name of the tun interface, such as tun0, utun4, etc. If this option is not provided, the OS will
                               generate a random one
