### ISSUE TITLE
Strip released library

### ISSUE THREAD

**Issue by MegatronKing** [tun2proxy/tun2proxy#114]
Now the release library is very fat because it contains debug information. I think the release version should add the `strip` option when compiling.

We can detect the library info:
```
file arm64-v8a/libtun2proxy.so
```
The output is:
```
ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, with debug_info, not stripped
```
A stripped library should be like this:
```
ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[md5/uuid]=bf30dce9d6fb4d521e5a7877635aee23, stripped
```

**Comment by mksafavi** [comment]
@ssrlive 
Hi. 
It seems like the strip config is reverted back:
https://github.com/tun2proxy/tun2proxy/blob/7fa530051c2858ef996e3c49e895696a8824cb25/Cargo.toml#L81
