### ISSUE TITLE
Wrap the export header file with `extern "C"` and  export declare

### ISSUE THREAD

**Issue by MegatronKing** [tun2proxy/tun2proxy#115]
If want to use the library in c++, we have to wrap the header file like this:
```c++
#ifdef __cplusplus
extern "C" {
#endif

/**
 * DNS query handling strategy
 * - Virtual: Use a virtual DNS server to handle DNS queries, also known as Fake-IP mode
 * - OverTcp: Use TCP to send DNS queries to the DNS server
 * - Direct: Do not handle DNS by relying on DNS server bypassing
 */
typedef enum Tun2proxyDns {
  Tun2proxyDns_Virtual = 0,
  Tun2proxyDns_OverTcp,
  Tun2proxyDns_Direct,
} Tun2proxyDns;

...

#ifdef __cplusplus
```

To link the library, We have to add export declare before the apis:
```c++

#if defined(WIN32)
#define TUN2PROXY_EXPORT __declspec(dllexport)
#else
#define TUN2PROXY_EXPORT __attribute__((visibility("default")))
#endif

TUN2PROXY_EXPORT int tun2proxy_with_fd_run(const char *proxy_url,
                          int tun_fd,
                          bool packet_information,
                          unsigned short tun_mtu,
                          enum Tun2proxyDns dns_strategy,
                          enum Tun2proxyVerbosity verbosity);
```

**Comment by MegatronKing** [comment]
🚀 Thanks for the quick fix. By the way, I have integrated this library into my android project and no issue has been found in testing so far. Thanks again.

**Comment by ssrlive** [comment]
Happy to hearing that.

**Comment by ssrlive** [comment]
Hi @MegatronKing, can you take some time to write a tutorial in the [wiki](https://github.com/tun2proxy/tun2proxy/wiki) on how to integrate tun2proxy into an Android project?

**Comment by MegatronKing** [comment]
> Hi @MegatronKing, can you take some time to write a tutorial in the [wiki](https://github.com/tun2proxy/tun2proxy/wiki) on how to integrate tun2proxy into an Android project?

Do you have a sample repo? I can submit a PR.

**Comment by ssrlive** [comment]
No. But you can create one, and I can add it to `tun2proxy` org.
