### ISSUE TITLE
DNS Policy Not Enforcing

### ISSUE THREAD

**Issue by tom1718** [tun2proxy/tun2proxy#116]
When i use "--dns direct"  in  MacOS，the DNS IP is still be Modified.

In my scenario, I only need to route traffic through the tun, not perform DNS resolution，i just want to use my internal DNS server.

**Comment by ssrlive** [comment]
Emm, `--dns direct` means your DNS packages will passed to the SOCKS5 server as normal UDP packages.
Maybe we have to reconsider the DNS logic? @blechschmidt

**Comment by tom1718** [comment]
Yes, sometimes it's only necessary to route the resolved traffic through a tun interface,it might be helpful to add an option that uses the system's default DNS @ssrlive

**Comment by blechschmidt** [comment]
> Emm, `--dns direct` means your DNS packages will traffic to the SOCKS5 server as normal UDP packages. Maybe we have to reconsider the DNS logic? @blechschmidt

To be honest, my understanding was that the desired behavior of `--dns direct` would be to not modify `/etc/resolv.conf`. At least that was what the behavior was when it was still called `none` in contrast to `virtual`. I would suggest the following behavior:

1. If `--dns direct` is specified without `--dns-addr`, we do not modify `/etc/resolv.conf`.
2. If `--dns direct` is specified with `--dns-addr`, we modify `/etc/resolv.conf` to contain these addresses. If they are not covered by a more specific route, they will use the proxy through UDP.

In the future we could also add an option called `--dns bypass` which parses `/etc/resolv.conf` and explicitly sets up the DNS server addresses like bypass IPs.
