### ISSUE TITLE
Tunnel Stats

### ISSUE THREAD

**Issue by EbrahimTahernejad** [tun2proxy/tun2proxy#117]
Having a get_stats function (C api) which provides upload/download would be nice.

**Comment by ssrlive** [comment]
It is beyond the scope of this project, you can implement this functionality in the upstream server, such as [this implementation](https://github.com/ShadowsocksR-Live/overtls/blob/7d0f529aaacefcdb146c30bfdfc8f1bcb406fdcc/src/android.rs#L138-L185).

**Comment by ssrlive** [comment]
Hi @EbrahimTahernejad , please test this branch https://github.com/tun2proxy/tun2proxy/tree/traffic and report your result here.
then decide whether to merge into the master branch.

**Comment by blechschmidt** [comment]
I don't see how this would affect performance by something other than a negligible amount. Internally, [`tokio::io::copy`](https://docs.rs/tokio/latest/src/tokio/io/util/copy.rs.html#272) calls [`poll_copy`](https://docs.rs/tokio/latest/src/tokio/io/util/copy.rs.html#75). That implementation also uses an 8 KB buffer and tracks state changes through the `Poll` mechanism. I don't see any essential difference between what your implementation does apart from using another abstraction layer through `await`.

**Comment by EbrahimTahernejad** [comment]
Thank you for considering my suggestion. I will test it ASAP

**Comment by EbrahimTahernejad** [comment]
are you sure this even works on iOS?
this was my first time running it and I got some weird errors.

I'll open another issue first

**Comment by EbrahimTahernejad** [comment]
The problem was the over tcp part.

**Comment by ssrlive** [comment]
the example above running fine in my project. I tested just now.

**Comment by ssrlive** [comment]
Test passed.
![image](https://github.com/tun2proxy/tun2proxy/assets/30760636/08dc6ab3-3a66-44d9-933d-6e4dafd8889b)

**Comment by MegatronKing** [comment]
@ssrlive  Thanks for your example code, but I have a question.

```obc
- (void)writingPacketFlow {
    if (_shouldStop) {
        return;
    }
    uint8_t buffer[2048];
    ssize_t len = read(self->_read_write_fd, buffer, sizeof(buffer));
    if (len > 0) {
        NSData* packet = [NSData dataWithBytes:buffer length:len];

        uint8_t protocol = (buffer[0] >> 4) & 0x0F;
        if (protocol == 4) {
            [self.packetFlow writePackets:@[ packet ] withProtocols:@[ @(AF_INET) ]];
        } else if (protocol == 6) {
            [self.packetFlow writePackets:@[ packet ] withProtocols:@[ @(AF_INET6) ]];
        } else {
            NSLog(@"Unknown protocol: %ld", (long)protocol);
        }
    }
    dispatch_async(_writeQueue, ^{ [self writingPacketFlow]; });
}
```
You can't guarantee that the data read from fd is a complete IP packet, right? A IP package may broken and wiil hit `Unknown protocol`.

**Comment by ssrlive** [comment]
Hmm... Based on my observation, there are some packets that are unrecognizable. I need to study them further.

**Comment by ssrlive** [comment]
Hmm... Based on my observation, there are some packets that are unrecognizable. I need to study them further.
Maybe we have to reconsider the reading logic.

![image](https://github.com/tun2proxy/tun2proxy/assets/30760636/c55af836-907f-4315-8278-de76cc26cb2c)

**Comment by ssrlive** [comment]
After an hour, I encountered 4 errors. Hmm, it seems there is still room for further improvement.

![image](https://github.com/tun2proxy/tun2proxy/assets/30760636/2d98a177-12b0-4ab1-b8e9-9910deb25520)

**Comment by MegatronKing** [comment]
@ssrlive You can try my code:
```objc
- (void)writingPacketFlow {
    if (_shouldStop) {
        return;
    }
    uint8_t buffer[2048];
    ssize_t len = read(self->_read_write_fd, buffer, sizeof(buffer));
    if (len > 0) {
        @autoreleasepool {
            NSData* input = [NSData dataWithBytes:buffer length:len];
            NSArray* packets = [self processIPPackets:input];
            for (NSData* packet in packets) {
                const uint8_t *bytes = [packet bytes];
                uint8_t protocol = (bytes[0] >> 4) & 0x0F;
                if (protocol == 4) {
                    [self.packetFlow writePackets:@[ packet ] withProtocols:@[ @(AF_INET) ]];
                } else if (protocol == 6) {
                    [self.packetFlow writePackets:@[ packet ] withProtocols:@[ @(AF_INET6) ]];
                } else {
                    NSLog(@"Unknown protocol: %ld", (long)protocol);
                }
            }
        }
    }
    dispatch_async(_writeQueue, ^{ [self writingPacketFlow]; });
}

- (NSArray *)processIPPackets:(NSData *)buffer {
    NSMutableArray *completedPackets = [[NSMutableArray alloc] init];
    NSMutableData* totalBuffer = [[NSMutableData alloc] init];
    [totalBuffer appendData: _pendingBuffer];
    [totalBuffer appendData: buffer];
    while ([totalBuffer length] > 0) {
        int offset = [self detectIPPacketOffset:totalBuffer];
        if (offset <= 0) {
            break;
        }
        NSData *completePacket = [totalBuffer subdataWithRange:NSMakeRange(0, offset)];
        [completedPackets addObject: completePacket];
        if (offset < totalBuffer.length) {
            NSData *remaining = [totalBuffer subdataWithRange:NSMakeRange(offset, totalBuffer.length - offset)];
            [totalBuffer setLength: 0];
            [totalBuffer appendData: remaining];
        } else {
            [totalBuffer setLength: 0];
        }
    }
    [_pendingBuffer setLength: 0];
    if (totalBuffer.length > 0) {
        [_pendingBuffer appendData: totalBuffer];
        [totalBuffer setLength: 0];
    }
    return [completedPackets copy];
}

- (int)detectIPPacketOffset:(NSData *)buffer {
    if ([buffer length] < 20) {
        return -1;
    }
    const uint8_t *bytes = [buffer bytes];
    uint8_t version = (bytes[0] & 0xF0) >> 4;
    if (version != 4 && version != 6) {
        return -1;
    }
    uint8_t headerLength = bytes[0] & 0x0F;
    headerLength *= 4;
    
    uint16_t totalLength = CFSwapInt16BigToHost(*(uint16_t *)(bytes + 2));
    if ([buffer length] < totalLength) {
        return -1;
    }
    return totalLength;
}
```

**Comment by ssrlive** [comment]
👌 @MegatronKing

**Comment by sudoconf** [comment]
@MegatronKing writingPacketFlow 函数是如何触发的?
