### ISSUE TITLE
Write unshare pid into a file for scripting

### ISSUE THREAD

**Issue by koitococo** [tun2proxy/tun2proxy#118]
In the current version, the --setup --unshare parameter combination provides an easy way to set up netns. However, the unshare pid only appears in the log, which means I have to check the log to get the pid, and then use `nsenter` to enter this namespace. This is inconvenient, especially for scripting needs.

A possible solution:
 add a parameter `--unshare-pidfile <UNSHARE_PIDFILE>` to write the unshare pid into a file. Afterwards, the pid can be obtained using `cat <UNSHARE_PIDFILE>`.
for example: `nsenter --preserve-credentials --user --net --mount --target $(cat $XDG_RUNTIME_DIR/tun2proxy_unshare.pid) fish`

**Comment by blechschmidt** [comment]
Has been merged. Thanks a lot!
