### ISSUE TITLE
"non-`--setup`" mode in Windows

### ISSUE THREAD

**Issue by ge9** [tun2proxy/tun2proxy#120]
Currently, Windows version implicitly uses `--setup` because creating a tun device itself requires admin privilege. 
However, I think it will be useful if we can use this tun device only for specific routes (like 10.0.0.0/24).
FYI, just disabling `--setup` in Windows configuration didn't work for me (it still sets the default route).

**Comment by ssrlive** [comment]
I don’t know the necessity of doing this. Moreover, according to my memory, if the routing table is not set, tun2proxy will not work. I’m not sure if my memory is accurate.
