### ISSUE TITLE
nearly all time out in windows 10

### ISSUE THREAD

**Issue by tcc-123** [tun2proxy/tun2proxy#121]
Hello, I am sure my proxy network is normal.
I used v2ray to open a proxy on port 33001 locally, but I cannot use TUN to access the Internet normally through your program.
I used [this tool to open TUN](https://github.com/xjasonlyu/tun2socks) before. Although it can work, the speed is very slow, and it even times out and reports errors most of the time.
My startup command is as follows：
`tun2proxy --proxy socks5://127.0.0.1:33001`

![image](https://github.com/tun2proxy/tun2proxy/assets/58293687/44c04bdf-e86c-4a38-92ba-98f5bd25a4d8)

I'm very confused and have no idea what to do. Thank you very much for your help.

**Comment by ssrlive** [comment]
```
tun2proxy --proxy socks5://127.0.0.1:33001 --bypass your_remote_server_ip
```

**Comment by tcc-123** [comment]
Oh, thanks a lot. I skipped this because I'm running on Windows.
It now occasionally loads, but there are two new problems.
One is that it still frequently times out (but on the web page instead of the console)
![image](https://github.com/tun2proxy/tun2proxy/assets/58293687/97b2dcb2-57f9-4595-8ebd-e31f1ed65fee)

The other is that the console is scrolling at a very high speed

**Comment by ssrlive** [comment]
so, use my proxy app https://github.com/ShadowsocksR-Live/overtls instead.

**Comment by tcc-123** [comment]
OK, thanks. 
I'll do some more research, maybe there's something wrong with my configuration.

**Comment by tcc-123** [comment]
Great, it's working now! It turns out that I remembered the bypass ip wrong. 
This is a really cool project, thanks, it deserves a star
