### ISSUE TITLE
Duplicated http proxy message sending

### ISSUE THREAD

**Issue by MegatronKing** [tun2proxy/tun2proxy#127]
During the test, I found another issue on iOS.

I use http proxy and virtual dns, when a client sends one http(not https) request, the proxy server will receive two or more `CONNECT` requests. Not always, but easily reproducible.

**Comment by blechschmidt** [comment]
I can't reproduce this on Linux and I don't have an iOS device to test on. Are these inside new TCP sessions to the proxy? Would it be possible for you to share a pcap file, ideally capturing the tunnel interface as well as the WAN interface?

**Comment by MegatronKing** [comment]
I dont know how to capture pcap on iOS device. I get a pcap from the proxy server side, wish to be helpful.

[reqable.com.pcapng.zip](https://github.com/user-attachments/files/15937297/reqable.com.pcapng.zip)

The request is `http://reqable.com`. And the first proxy request is port `54494`, and the second is `54496`.

**Comment by MegatronKing** [comment]
I print the log from the library.

```
00:10:57.043211+0800	vpn	log [2024-06-23 00:10:57 INFO  tun2proxy] - tun2proxy 0.2.22 starting...
默认	00:10:57.043262+0800	vpn	log [2024-06-23 00:10:57 INFO  tun2proxy] - Proxy http server: 192.168.0.100:8080
默认	00:10:58.692470+0800	vpn	log [2024-06-23 00:10:58 TRACE tun2proxy] - Session count 1
默认	00:10:58.692585+0800	vpn	log [2024-06-23 00:10:58 DEBUG tun2proxy] - Virtual DNS query: www.apple.com. -> 198.18.0.0
默认	00:10:58.696321+0800	vpn	log [2024-06-23 00:10:58 TRACE tun2proxy] - Session count 2
默认	00:10:58.715887+0800	vpn	log [2024-06-23 00:10:58 DEBUG tun2proxy] - Virtual DNS query: www.icloud.com. -> 198.18.0.1
默认	00:11:00.059854+0800	vpn	log [2024-06-23 00:11:00 TRACE tun2proxy] - Session count 3
默认	00:11:00.060115+0800	vpn	log [2024-06-23 00:11:00 DEBUG tun2proxy] - Virtual DNS query: reqable.com. -> 198.18.0.2
默认	00:11:00.065448+0800	vpn	log [2024-06-23 00:11:00 TRACE tun2proxy] - Session count 4
默认	00:11:00.306005+0800	vpn	log [2024-06-23 00:11:00 TRACE tun2proxy] - Session count 5
默认	00:11:00.374689+0800	vpn	log [2024-06-23 00:11:00 INFO  tun2proxy] - Beginning #3 TCP 10.1.10.1:55461 -> 198.18.0.2:80
默认	00:11:00.379344+0800	vpn	log [2024-06-23 00:11:00 INFO  tun2proxy] - Beginning #4 TCP 10.1.10.1:55463 -> 198.18.0.2:80
默认	00:11:00.585736+0800	vpn	log [2024-06-23 00:11:00 TRACE tun2proxy] - Session count 6
默认	00:11:00.590042+0800	vpn	log [2024-06-23 00:11:00 INFO  tun2proxy] - Beginning #5 TCP 10.1.10.1:55465 -> 198.18.0.2:443
默认	00:11:01.767168+0800	vpn	log [2024-06-23 00:11:01 TRACE tun2proxy] - Session count 7
默认	00:11:01.768389+0800	vpn	log [2024-06-23 00:11:01 DEBUG tun2proxy] - Virtual DNS query: 28-courier.push.apple.com. -> 198.18.0.3
默认	00:11:01.773818+0800	vpn	log [2024-06-23 00:11:01 TRACE tun2proxy] - Session count 8
默认	00:11:01.803817+0800	vpn	log [2024-06-23 00:11:01 INFO  tun2proxy] - Beginning #7 TCP 10.1.10.1:49842 -> 198.18.0.3:5223
默认	00:11:08.666965+0800	vpn	log [2024-06-23 00:11:08 DEBUG tun2proxy] - Virtual DNS session error: timed out
默认	00:11:08.667707+0800	vpn	log [2024-06-23 00:11:08 TRACE tun2proxy] - Session count 7
默认	00:11:08.667843+0800	vpn	log [2024-06-23 00:11:08 DEBUG tun2proxy] - Virtual DNS session error: timed out
默认	00:11:08.668051+0800	vpn	log [2024-06-23 00:11:08 TRACE tun2proxy] - Session count 6
默认	00:11:10.067276+0800	vpn	log [2024-06-23 00:11:10 DEBUG tun2proxy] - Virtual DNS session error: timed out
默认	00:11:10.067534+0800	vpn	log [2024-06-23 00:11:10 TRACE tun2proxy] - Session count 5
默认	00:11:11.774141+0800	vpn	log [2024-06-23 00:11:11 DEBUG tun2proxy] - Virtual DNS session error: timed out
默认	00:11:11.775217+0800	vpn	log [2024-06-23 00:11:11 TRACE tun2proxy] - Session count 4
默认	00:11:21.067806+0800	vpn	log [2024-06-23 00:11:21 INFO  tun2proxy] - Shutdown received
```
We can see two proxy requests were sent by tun2proxy.
```
默认	00:11:00.374689+0800	vpn	log [2024-06-23 00:11:00 INFO  tun2proxy] - Beginning #3 TCP 10.1.10.1:55461 -> 198.18.0.2:80
默认	00:11:00.379344+0800	vpn	log [2024-06-23 00:11:00 INFO  tun2proxy] - Beginning #4 TCP 10.1.10.1:55463 -> 198.18.0.2:80
```

**Comment by blechschmidt** [comment]
Looking at the `User-Agent` header, I assume that this request is sent by custom software. How is that request to `reqable.com` generated, i. e. which library do you use? Does this happen with HTTP requests from other tools?

I know basically nothing about iPhones, can you do a curl or something like that there to rule out that some library that you are using is building something like a connection pool? Does this also occur with a tool like https://apps.apple.com/de/app/icurlhttp/id611943891?

**Comment by MegatronKing** [comment]
The request was sent by my app, so I can make sure that this request is only sent once. Of course, this issue is not limited to my app, other apps have it too. In fact, I discovered this when I was testing other apps.

My app: https://apps.apple.com/us/app/reqable/id6473166828

**Comment by blechschmidt** [comment]
> We can see two proxy requests were sent by tun2proxy.
> 
> ```
> 默认	00:11:00.374689+0800	vpn	log [2024-06-23 00:11:00 INFO  tun2proxy] - Beginning #3 TCP 10.1.10.1:55461 -> 198.18.0.2:80
> 默认	00:11:00.379344+0800	vpn	log [2024-06-23 00:11:00 INFO  tun2proxy] - Beginning #4 TCP 10.1.10.1:55463 -> 198.18.0.2:80
> ```

This indicates that two requests are sent **to** tun2proxy, not **by** tun2proxy.

**Comment by MegatronKing** [comment]
This is weird, according to the log, two TCP connection requests were indeed received from tun. I noticed that after my server received two proxy requests, the second request was blocked while reading subsequent data.

**Comment by MegatronKing** [comment]
I don't know why this issue occurs on iOS, but the current investigation has shown that it is not related to tun2proxy, so I closed this issue.
