### ISSUE TITLE
Add an option to diable UDP proxying.

### ISSUE THREAD

**Issue by MegatronKing** [tun2proxy/tun2proxy#128]
In the current design, UDP traffic must be forwarded to socks5 server, if we use http server, will get an error `Protocol not supported by HTTP proxy`. In many cases, we don't actually need a UDP proxy.

**Comment by MegatronKing** [comment]
I use tun2proxy for web debugging proxy, users only pay attention to the HTTP protocol, not UDP. Therefore, we just need to implement a MITM web proxy server. The web proxy server is simple to implement, but it will cause all UDP traffic to be blocked in tun2proxy. 

I tested on iOS devices and found that every network request would first send a DNS query instead of using the device cache. Since the web server cannot accept UDP, this will cause all subsequent TCP connections to fail. I am currently using the virtual DNS strategy to temporarily solve this issue, but it is not the best solution.

In addition, HTTP3 also uses the UDP protocol, which will also make it impossible for the Web proxy server to handle it.

**Comment by blechschmidt** [comment]
Given that you seem to integrate tun2proxy into commercial software, how about contributing back a bit and submitting a PR?

**Comment by MegatronKing** [comment]
> Given that you seem to integrate tun2proxy into commercial software, how about contributing back a bit and submitting a PR?

I wish I could, but I'm not a Rust programmer.
