### ISSUE TITLE
Provide Benchmark

### ISSUE THREAD

**Issue by Morrigan-Ship** [tun2proxy/tun2proxy#133]
Please provide a Benchmark for comparing [tun2proxy](https://github.com/tun2proxy/tun2proxy) VS [tun2socks](https://github.com/xjasonlyu/tun2socks)

like speed test ping stability or anything...

**Comment by ssrlive** [comment]
Any mention of this [crap](https://github.com/xjasonlyu/tun2socks) that has been poorly documented for decades is an insult to us.

How about you complete this benchmark comparison?

**Comment by Morrigan-Ship** [comment]
ha? :/ crap?
it have good speed but using many memory
my mean from benchmark in a chart
for example our project will:
- reduc 20% memory usage
- faster speed
- faster connect
- Kill swich feature
- UDP features unlike tun2socks
this just an example
my mean wasnt insult

**Comment by ssrlive** [comment]
To be honest, I have never successfully run that rubbish. A thing that never treats its users as human beings is not worth paying attention to, right? ! I'm not interested anyway.

**Comment by ssrlive** [comment]
To this day, a large number of questions in the discussion forum are still about how to make this rubbish run, but the author just does not answer, admiring the despair of these people, how can you fall in love with this rubbish?
![image](https://github.com/user-attachments/assets/ce2e8afd-c65e-43a8-94c5-4654c0a329a1)
