### ISSUE TITLE
Arm64 docker support 

### ISSUE THREAD

**Issue by flexxxxer** [tun2proxy/tun2proxy#140]
# What does the feature entail?
Support for Docker image launch on Arm64-based systems.

# Why is this feature important?
At the moment, for several VPS providers, the cost of Arm64-based systems is two times lower than for x86-based systems: I can get twice as many Arm cores for the same price as x86 => more peoples can use my self-hosted privacy frontend instances that use tun2proxy + xray-core to bypass ip-restrictions (using mullvad/protonvpn as proxies for outbound traffic) because of people's intense use of my privacy-frontends, what sometimes looks like a bot attack.

# PS
Github supports building for Arm64 through Docker Buildx + QEMU. Maybe within a day of publishing this issue I will send a pull request with the changes for providing Arm64 support. Help and suggestions welcome!

**Comment by flexxxxer** [comment]
Using Dockerfile from [f2calv/multi-arch-container-rust](https://github.com/f2calv/multi-arch-container-rust/blob/main/Dockerfile) as example i'm added support for building image for arm64 (and arm/v7 too). Few minutes ago tested locally using `docker buildx build --platform linux/amd64,linux/arm64 -t t2p-test:0.0.1 --output type=local,dest=./output .` and its actually works. I plan to send pull-request within a day. Any objections?

**Comment by Paper-Dragon** [comment]
maybe use docker/buildx action is better.
https://github.com/docker/buildx
