### ISSUE TITLE
add command line arguments for virtual dns 

### ISSUE THREAD

**Issue by dvir101** [tun2proxy/tun2proxy#142]
Hi,

I’d like to request control over the start_addr and prefix_len in the virtual DNS. I don’t have permission to submit a PR, but here are the diffs
[diffs.txt](https://github.com/user-attachments/files/16781056/diffs.txt)

**Comment by ssrlive** [comment]
Applied in commit https://github.com/tun2proxy/tun2proxy/commit/8c28f2e0004f66db5a172fb786d3bd82ef602d68

**Comment by dvir101** [comment]
Thanks! @ssrlive @blechschmidt
