### ISSUE TITLE
The memory usage is too high

### ISSUE THREAD

**Issue by modasi** [tun2proxy/tun2proxy#153]
Basic operation already consumes 150-200MB of memory. For a tun2socks-like implementation, low memory usage is a core requirement, especially in mobile or router environments. Running sing-box, which is based on Go, in exactly the same environment only requires 30MB. Theoretically, the reason for choosing a Rust implementation is that memory usage should be lower than Go.

**Comment by ssrlive** [comment]
![image](https://github.com/user-attachments/assets/e6ecc763-2704-4a4c-95af-da4d6e9dff9c)
