### ISSUE TITLE
recv udp error

### ISSUE THREAD

**Issue by antoniovalenzuela** [tun2proxy/tun2proxy#164]
Hi, I'm testing udpgw_server

It works perfectly with DNS

I'm trying to register a SIP line udp 5060, but it usually fails. I try again 10 to 20 times and sometimes it connects.

tun2proxy
![imagen](https://github.com/user-attachments/assets/88a3272f-738f-45e9-90e0-a97ab992495c)

udpgw_server
![imagen](https://github.com/user-attachments/assets/cc11fb50-4278-411d-b341-050611b67bfc)

I retry many times until it connects
![imagen](https://github.com/user-attachments/assets/4c276e67-721b-431b-a5b5-e9c3ee1f4ba7)

I have also tried modifying the mtu and timeout parameters.

UdpGw and SIP server are on the same subnet, direct connection tests work without problems.

**Comment by ssrlive** [comment]
I have thought about this problem, that is, when the destination address of your UDP datagram is located on the local network, and your UdpGw server is running on the public network, then the UDP data will not be able to be delivered to the destination address.

Have you considered a solution to this problem?

PRs welcome.

**Comment by antoniovalenzuela** [comment]
tun2proxy runs on a VPS in the cloud. 

udpgw runs on a router with OpenWRT on my LAN, which in creates the remote socks5 over the VPS with a SSH tunnel.

SIP server UDP 5060 over RPI on the same LAN. 

So I'm just trying to register a phone number. 

VPS tun2proxy -> router socks5 + udpgw -> SIP UDP 5060

Connectivity works, on the SIP server I see all the incoming connections. 

The problem maybe is with udpgw, when receiving the response packet from the SIP, it usually does not reach the source. I rarely receive 200 ok, most of them return time out. 

I have no problems with DNS, all UDP 53 queries respond well. 

Actually I do tests with the SIP server, it is a laboratory to check the SIP phone registry using udpgw.

**Comment by sujiacong** [comment]
The original design intention of udpgw is to deploy it on a device that is reachable by the proxy server device. All proxy traffic is ultimately routed and forwarded on the proxy server.

I don’t quite understand why you said udpgw is deployed on OpenWRT on the LAN and can forward UDP.

OpenWRT on your LAN is connected to VPS through ssh. Between OpenWRT and VPS, only OpenWRT can connect to VPS, and VPS cannot connect to openWRT.

The traffic received by udpgw is forwarded by the proxy, that is, the traffic is ultimately routed on the VPS, and the VPS cannot connect to openWRT. How can it be connected?

**Comment by antoniovalenzuela** [comment]
These are just tests.

I can't open NAT on my LAN because it's a 5G Mobile ISP, that's why I use the "pivot" VPS with SSH tunnels.

I can use udpgw on the Router or directly on RPI, the results are identical.

All DNS queries from the VPS to RPI work perfectly.

I wanted to test the connections to the SIP service, this is where I have the problems. I send SIP phone register, some work, most with a timed out message "recv udp error"

I can use SIP on TCP 5060, but UDP is the default protocol, that's why I did the lab with updgw. 

I opened the incident without expecting a solution, it's not a productive environment. Anyway, the concern remains about how it works with the SIP service.

![imagen](https://github.com/user-attachments/assets/02bed4fd-eb55-4354-bce0-521844708a2d)

**Comment by sujiacong** [comment]
OK, I understand now. You have established a reverse SSH connection [ssh -R] from your router to the VPS, which I previously misunderstood as a SOCKS5 tunnel [ssh -D].

So, in your deployment diagram, when you access socks5://127.0.0.1:9000, you are actually accessing port 9000 on your router,

Does that mean port 9000 on your router is a SOCKS5 proxy service?

If that's the case, and both the SOCKS5 proxy and udpgw and RPI are reachable, then UDP forwarding should be possible.

Can you use tcpdump to capture packets on the router where udpgw is deployed?
Check if UDP packets are being sent and if there is any response after sending.

Run the following packet capture command on the router:
tcpdump -i any port 5060 and udp -s0 -w 5060.pcap -vv

**Comment by antoniovalenzuela** [comment]
I used the "badvpn" project and I can connect to the SIP UDP server. All packets return to the origin.

It would be necessary to check if there is an issue in this project. I will close the incident, thanks.

**Comment by sujiacong** [comment]
Thank you for your feedback. I will test your deployment scenario when I have time, and if there are any fixes, I will reply here.

**Comment by antoniovalenzuela** [comment]
> OK, I understand now. You have established a reverse SSH connection [ssh -R] from your router to the VPS, which I previously misunderstood as a SOCKS5 tunnel [ssh -D].
> 
> So, in your deployment diagram, when you access socks5://127.0.0.1:9000, you are actually accessing port 9000 on your router,
> 
> Does that mean port 9000 on your router is a SOCKS5 proxy service?
> 
> If that's the case, and both the SOCKS5 proxy and udpgw and RPI are reachable, then UDP forwarding should be possible.
> 
> Can you use tcpdump to capture packets on the router where udpgw is deployed? Check if UDP packets are being sent and if there is any response after sending.
> 
> Run the following packet capture command on the router: tcpdump -i any port 5060 and udp -s0 -w 5060.pcap -vv

SSH router creates the remote listener 0.0.0.0:9090 in the VPS. This 9090 is the socks to allow access from VPS to the LAN (through router)
