### ISSUE TITLE
Cannot handshake client 31.13.68.169:80 tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by leetomlee123** [tun2proxy/tun2proxy#170]
Cannot handshake client 31.13.68.169:80 tls: first record does not look like a TLS handshake

**Comment by moxcomic** [comment]
> Cannot handshake client 31.13.68.169:80 tls: first record does not look like a TLS handshake

Have you solved this problem? How did you resolve it?

**Comment by leetomlee123** [comment]
> > Cannot handshake client 31.13.68.169:80 tls: first record does not look like a TLS handshake
> 
> Have you solved this problem? How did you resolve it?

gave up
